#!/usr/bin/env bash

set -Eeuo pipefail
umask 077
export LC_ALL=C

dotenv_file=.env
dotenv_tmp=

cleanup() {
	if [[ -n "$dotenv_tmp" ]]; then
		rm -f "$dotenv_tmp"
	fi
}
trap cleanup EXIT

fail() {
	printf 'setup: %s\n' "$*" >&2
	exit 1
}

read_value() {
	local prompt=$1
	local value

	while true; do
		printf '%s' "$prompt" >&2
		IFS= read -r value || fail 'input interrupted'
		if [[ -n "${value//[[:space:]]/}" ]]; then
			printf '%s' "$value"
			return
		fi
		printf 'A value is required.\n' >&2
	done
}

read_secret() {
	local prompt=$1
	local value

	printf '%s' "$prompt" >&2
	IFS= read -r -s value || fail 'input interrupted'
	printf '\n' >&2
	printf '%s' "$value"
}

read_required_secret() {
	local prompt=$1
	local value

	while true; do
		value=$(read_secret "$prompt")
		if [[ -n "${value//[[:space:]]/}" ]]; then
			printf '%s' "$value"
			return
		fi
		printf 'A value is required.\n' >&2
	done
}

generate_session_secret() {
	local value

	if command -v openssl >/dev/null 2>&1; then
		value=$(openssl rand -hex 32) || return 1
	else
		command -v od >/dev/null 2>&1 || return 1
		command -v tr >/dev/null 2>&1 || return 1
		value=$(head -c 32 /dev/urandom | od -An -v -tx1 | tr -d '[:space:]') || return 1
	fi

	[[ $value =~ ^[0-9a-f]{64}$ ]] || return 1
	printf '%s' "$value"
}

validate_dotenv_value() {
	local name=$1
	local value=$2

	if [[ $value == *$'\r'* || $value == *$'\n'* || $value == *"'"* ]]; then
		fail "$name must not contain newlines or single quotes"
	fi
}

write_dotenv_value() {
	# Compose treats single-quoted dotenv values literally, so values such as
	# '$' and '#' are preserved without interpolation or comment parsing.
	printf "'%s'" "$1"
}

[[ ! -e $dotenv_file && ! -L $dotenv_file ]] || fail '.env already exists; remove it before running make setup'

printf 'Redlaunch VPS setup\n\n' >&2
google_client_id=$(read_value 'Google Client ID: ')
google_client_secret=$(read_required_secret 'Google Client Secret: ')
auth_session_secret=$(read_secret 'Auth session secret (optional; press Enter to generate): ')
authorized_email=$(read_value 'First authorized email address: ')

validate_dotenv_value GOOGLE_CLIENT_ID "$google_client_id"
validate_dotenv_value GOOGLE_CLIENT_SECRET "$google_client_secret"
validate_dotenv_value AUTH_SESSION_SECRET "$auth_session_secret"

if [[ -z $auth_session_secret ]]; then
	auth_session_secret=$(generate_session_secret) || fail 'could not generate a secure auth session secret'
	printf 'Generated a secure auth session secret.\n' >&2
elif [[ ${#auth_session_secret} -lt 32 ]]; then
	fail 'AUTH_SESSION_SECRET must contain at least 32 characters'
fi

dotenv_tmp=$(mktemp .env.tmp.XXXXXX) || fail 'could not create a temporary .env file'
chmod 600 "$dotenv_tmp"
{
	printf '# Generated by make setup.\n'
	printf 'GOOGLE_CLIENT_ID='
	write_dotenv_value "$google_client_id"
	printf '\nGOOGLE_CLIENT_SECRET='
	write_dotenv_value "$google_client_secret"
	printf '\nGOOGLE_REDIRECT_URL='
	write_dotenv_value 'http://localhost:8080/auth/google/callback'
	printf '\nAUTH_SESSION_SECRET='
	write_dotenv_value "$auth_session_secret"
	printf '\nAUTH_COOKIE_SECURE='
	write_dotenv_value 'false'
	printf '\n'
} >"$dotenv_tmp" || fail 'could not write .env'
mv "$dotenv_tmp" "$dotenv_file" || fail 'could not install .env'
dotenv_tmp=

# Ensure values already exported in the VPS shell cannot override the values
# entered during this setup run when Compose interpolates the .env file.
unset GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET GOOGLE_REDIRECT_URL AUTH_SESSION_SECRET AUTH_COOKIE_SECURE

printf '\nAdding the first authorized email...\n' >&2
docker compose run --rm --build app auth-add-email --email "$authorized_email"

printf '\nBuilding and starting Redlaunch...\n' >&2
docker compose up -d --build

printf '\nRedlaunch is running.\n' >&2
